project:
  type: website
  output-dir: _output

metadata-files:
  - samples/content-engineering/_sidebar.yaml
  - samples/technical-writing/_sidebar.yaml
  - samples/copywriting/_sidebar.yaml
  - samples/developer-advocacy/_sidebar.yaml

website:
  title: "Portfolio"
  favicon: assets/headshot.png
  navbar:
    left:
      - samples/content-engineering/index.qmd
      - samples/technical-writing/index.qmd
      - samples/copywriting/index.qmd
      # - samples/developer-advocacy/index.qmd
    right:
      - cv.qmd
      - text: "{{< fa brands github >}}"
        href: https://github.com/beck-chan
      - text: "{{< fa brands linkedin >}}"
        href: https://linkedin.com/in/beck-chan
      - text: "{{< fa envelope >}}"
        href: mailto:rebecca.ht.chan@gmail.com
      - text: "{{< fa phone >}}"
        href: tel:1-250-885-6801
      # - text: "Contact"
      #   menu:
      #   - text: "{{< fa brands github >}} **GitHub** &bull; beck-chan"
      #     href: https://github.com/beck-chan
      #   - text: "{{< fa brands linkedin >}} **LinkedIn** &bull; beck-chan"
      #     href: https://linkedin.com/in/beck-chan
      #   - text: "{{< fa envelope >}} rebecca.ht.chan@gmail.com"
      #     href: mailto:rebecca.ht.chan@gmail.com
      #   - text: "{{< fa phone >}} +1 (250) 885-6801"
      #     href: tel:1-250-885-6801

  sidebar: 
    style: docked
    border: false

  search:
    location: navbar

  # page-footer: 
  #   background: "#ff6162"
  #   foreground: "#fee3e5"
  #   left: 
  #     - text: <a href="https://github.com/beck-chan/portfolio/releases">Releases</a>
  #   right:
  #     - text: <a href="https://github.com/beck-chan"><i class="fa-brands fa-github"></i></a> <a href="https://www.linkedin.com/in/beck-chan"><i class="fa-brands fa-linkedin"></i></a> <a href="mailto:rebecca.ht.chan@gmail.com"><i class="fa fa-envelope"></i></a> <a href="tel:1-250-885-6801"><i class="fa fa-phone"></i></a>

format:
  html:
    page-layout: full
    grid:
      body-width: 1000px
      sidebar-width: 300px
    theme:
      light: assets/styles.scss
    toc: true
    link-external-newwindow: true
  
filters:
  - timeline
  - tachyons