project:
  type: website
  output-dir: _output

metadata-files:
  - samples/content-engineering/_sidebar.yaml
  - samples/technical-writing/_sidebar.yaml
  - samples/copywriting/_sidebar.yaml
  - samples/developer-advocacy/_sidebar.yaml

website:
  title: "Portfolio"
  favicon: assets/headshot.png
  navbar:
    left:
      - samples/content-engineering/index.qmd
      - samples/technical-writing/index.qmd
      - samples/copywriting/index.qmd
      # - samples/developer-advocacy/index.qmd
    right:
      - cv.qmd
      - text: "{{< fa brands github >}}"
        target: _blank
        href: https://github.com/beck-chan
      - text: "{{< fa brands linkedin >}}"
        target: _blank
        href: https://linkedin.com/in/beck-chan
      - text: "{{< fa envelope >}}"
        href: mailto:rebecca.ht.chan@gmail.com
        target: _blank

  sidebar: 
    style: docked
    border: false

  search:
    location: navbar

format:
  html:
    page-layout: full
    grid:
      body-width: 1000px
      sidebar-width: 300px
      margin-width: 500px
    theme:
      light: assets/styles.scss
    highlight-style: assets/code.theme
    code-overflow: wrap
    toc: true
    link-external-newwindow: true
  
filters:
  - timeline
  - tachyons