---
title: "Tracking Cookies"
subtitle: "JavaScript SDK"
categories: ["Developer Content", "JavaScript SDK", "Referrals & Attributions", "eCommerce", "Software as a Service", "Marketing Technology", "SaaSquatch"]
---

> I owned this entire guide from start to finish. 
>
> For this endeavour I researched and familiarized myself with [First-party cookie recipes](https://web.dev/articles/first-party-cookie-recipes){target="_blank"}.
> 
> Any links to guides I did not author have been removed for this archived version below.


As of June 2020, SaaSquatch has enabled the usage of 1st Party Cookies to accommodate a wider industry shift towards the increased protection of end user privacy.

SaaSquatch uses first-party cookies for referral attribution&mdash;the process of connecting a referred participant to the person who made the referral. The cookies are based on UTM parameters passed through the URL. By placing `squatch.js` on your landing page, it is able to read the UTM parameters and create a valid first-party cookie that’s in compliance with all browsers.

## Set up first-party cookies

We recommend that all implementations that make use of our referral cookie adhere to the following instructions to enable usage of first-party cookies: Make sure your landing page and your signup page exist on the same domain Add `squatch.js` to your landing page. This sets the first-party cookie. Place `squatch.js` on the signup page where your users are upserted. This reads the first-party cookie.

Here’s how it works:

1. `squatch.js` reads _saasquatch from the URL and stores a first-party cookie on the specified landing page's domain.
2. It automatically sets the cookies field on users during an upsert.
3. It reads the first-party cookie during use of autofill.

## Attribution Preference Hierarchy
As there are several ways to attribute a referred participant to a referrer, the connection will always be linked following the below scheme:

1. Explicit inclusion of a referredByCodes either via `squatch.js` or the REST API will always override any identified cookie.
2. If a referral code is not included directly with a user upsert, then `squatch.js` will look for the first-party cookie and make the attribution.
3. If no first-party cookie exists and a third-party cookie is available through a compatible browser, the 3rd-party cookie will be detected and applied.

#### Citation

[SaaSquatch Help Center: View Original Guide](https://docs.saasquatch.com/developer/squatchjs/cookies){.button}