---
title: "Honor the Human with ValidMind"
subtitle: "Blog Post"
categories: ["Blog", "Artificial Intelligence (AI)", "EU AI Act", "AI Risk", "Model Risk Management", "Risk Governance", "ValidMind"]
---

> I owned this blog post from start to finish.
> 
> Any links to guides I did not author have been removed for this archived version.

The threat of technology is nothing new. When the printing press emerged in Europe in the early 15th century, it introduced the idea that occupations could be overwritten by automation &mdash; gone were the days of pious monks toiling in dim light over delicate sheets of parchment, illuminating every manuscript meticulously by hand. But what sprung forth from volumes inked with remarkable speed and accuracy by machinery was the democratization of information, heralding a new age of literacy and imagination.

In 1746, a member of the British intelligentsia by the name of Samuel Johnson was commissioned to create A Dictionary of the English Language. Johnson famously boasted that he alone would be able to complete the project in a fraction of the 40 long years it took 40 different scholars from the Académie Française to complete their version &mdash; thanks in part to technological advances.

While he did not make good on his claim of only three years, Johnson managed the feat in under eight &mdash; a period during which he continued to add to his portfolio as one of the most prolific authors of his era. Consider for a moment instead innumerable instances of a text, produced painstakingly by hand and each page subject to all the realms of human error in an alternate reality where the hold of the printing press never took place.

Very few would argue that this tedium would be preferable, nor would very many of us agree to give up the many other tools that allow us to live with ease. Still, a deep insecurity lurks within the human psyche &mdash; a fear that one day we will be rendered obsolete by machines wrought from none other than our own innovation.

A chilling prophecy, a narrative so often repeated in disillusioned visions of our dystopian future. Yet Caecus, a politician and writer from the Roman Republic who lived over 2000 years ago, offered a more optimistic assessment of our capabilities as Homo faber &mdash; "human, the maker." Through the ingenious use of tools, each person is the architect of their own destiny.

## A model reality

Models, loosely defined as a simulation designed to help analyze and predict reality, have been used to fortify humanity’s understanding of the universe around us as far back as classical antiquity. From ancient theories of philosophy and astronomy to more modern concepts of physics and economics, tools like models enable us to more fully grasp abstract information and as a result drive concrete change.

Many consider the advent of artificial intelligence (AI) as somewhere in the mid-20th century, thanks to the works of Allen Newell and Herbert A. Simon, experts in computer science and cognitive psychology who together created computer programs such as the Logic Theorist. But the idea of mimicking human cognition finds its nascency again in the early days of civilization: in an example from the west, classical philosophers argued that patterns of thought were not unlike systemic and mechanical processes &mdash; therefore, they could also be replicated.

With the 20th century came an incredible realization of this profound tenet, as advances in spheres such as statistics and computing radically influenced decisions made in finance and beyond &mdash; changes that continue to shift the macroeconomic tides that wash all over the world. Information and tasks can now be processed at a speed and volume almost incomprehensible to human understanding &mdash; think compressing 40 years into 40 seconds. Using technology, humans have even been able to manipulate the passage of time.

## Autonomy through automation

From setting our alarms with Alexa to trusting the weather forecast’s estimate as to when the sun will be at its zenith, technology is woven into the very fabric of our being. Despite our apprehensions, most of us recognize that automation grants us autonomy to shape the future by streamlining the present. By removing the obstacle of how to accomplish a task, we can instead focus on the expanded possibilities of what else we can do with the resources made available by automation.

Let’s transpose ourselves again into the alternate reality where automation is eschewed instead of embraced: you approach a bank to request a loan, and a representative spends a week investigating your financial history to determine whether or not you qualify under the institution’s criteria.

The mere idea is maddening &mdash; you know that there is a much more effective, efficient, and accurate method &mdash; one where time and human cost is vastly reduced simply by leaning on the use of automation somewhere along the way. Similarly, you would likely be as frustrated by a process governed only by cold calculation, one where human oversight was absent and nuance was easily overlooked by impartial mathematics.

## (Hu)man in the machine

Ideal automation, therefore, marries both the human and the machine &mdash; a dialogue where both elements are intertwined and interact at various parts along the journey. Even Johnson’s patrons, who presumably had access to the same printing press as he did, recognized the need for an expert in the loop &mdash; someone who’s authority and input served as a control for the accuracy and quality of the output.

The Artificial Intelligence Act, a regulatory framework governing the use of AI proposed by the European Union, highlights human oversight in Article 14. Outlined in this section is the intrinsic involvement of human intervention, as well as measures to ensure that this governance is adhered to. At no point in the process is the human eliminated &mdash; in fact, one could conclude that the human has been elevated.

With great responsibility, comes great demand. What then is the perfect balance between automation and agency? For model developers, who are tasked with designing models to satisfy business needs, an interwoven exchange can look like intuitive assistance when producing documentation to be in line with regulatory requirements.

Accurate and thorough documentation plays an integral role in moving a model forward in the model lifecycle, serving as the cornerstone of the effective challenge process &mdash; the involvement of objective but informed parties who can help evaluate and improve models. Yet documentation is where many developers stumble, diverting precious time and resources better spent on more glamorous tasks, despite available templates established by best practice.

::: {.callout}
ValidMind’s approach to model documentation puts the human first, starting the conversation between developer and model using automation. Your model cannot yet speak for itself, but until then &mdash; there’s ValidMind.

:::

#### Citation

[ValidThoughts: View original post](https://validmind.com/blog/honor-the-human-with-validmind/){.button}