---
title: "Takeaways from Open Source in Finance Forum: Future of Fintech, OSS, and GenAI"
subtitle: "Blog Post"
categories: ["Blog", "Artficial Intelligence (AI)", "Generative AI", "Large Language Models", "Open-Source", "ValidMind"]
---

> I owned this blog post from start to finish.

The Fintech Open Source Foundation (FINOS) hosted its annual Open Source in Finance Forum in New York (OSFF NY) last week, attended by several members of ValidMind. Distinguished speakers representing prominent names in software and financial services led discussions on open-source ideologies, industry best practices, and projections. Of note were the many panels on artificial intelligence (AI), including deep dives into the use of Generative AI (GenAI) within financial services and software development as a whole.

GitHub — a service almost intrinsically linked with the idea of open source — hosted two sessions that focused on demonstrating the organization’s OpenAI tool, GitHub Copilot. Through the democratization of AI through Copilot, GitHub representatives argued that the barrier for entry to begin developing has been drastically lowered. Claiming to "maximize developer happiness, increase developer productivity, [and] accelerate software development" with its offering that includes suggested resolutions for proactively identified issues, GitHub’s outlook is that AI simplifies and enhances workflows for individuals and institutions enabling innovation and increased oversight — a philosophy we share here at ValidMind.

But the increased adoption of "non-traditional" models — that is, large language models (LLMs) or other types of GenAI models that produce outputs that are non-deterministic and unpredictable but have the benefit of more flexible applications and advanced scope beyond initial trained datasets — is not without its challenges. Panelists and participants at OSFF NY discussed and debated topics such as the unexpected intricacies when adapting open source licenses in the age of LLMs, or whether or not LLMs have the ability to tackle generating, reviewing, and utilizing complex documents required during key processes in financial services, and more. From legal ramifications to process practicalities, the question of AI expansion is not if but when and how best executed.

Growing pains notwithstanding, during the panel Making GenAI a Tool for Everyone, Colin Eberhardt, CTO of Scott Logic, proposed that soon it would be difficult to imagine a world before AI at the pace it is permeating every aspect of our lives. However, despite the significant and rapid increase in GenAI usage in many sectors such as mass media and law, statistics for financial services are lagging behind. While the apprehension is understandable for an industry so steeped in standardization and ruled by regulation, the community and conversation at OSFF NY posits that we are at the precipice of a phenomenal restructuring of our reality thanks to AI, with open-source software leading the charge.

To wrap up the organization’s keynote address on the final day of the conference, FINOS announced the inauguration of their AI Readiness Governance Framework, along with the next stage of their AI Readiness project — an open-source initiative that aims to manage the onboarding, development, and utilization of AI-based solutions to help dissolve the aforementioned reticence when it comes to GenAI adoption currently present within financial services. Reflecting their goal of fostering open source, open standards, and collaborative software development practices in financial services, FINOS now invites the wider community to join them in "developing and operationalizing frameworks, policies, and tools for the effective, safe, trustworthy, and compliant deployment of generative AI technologies."


::: {.callout}
Community creates change, and transparency turns into trust — which is why in late February of 2024, we shifted the ValidMind product library to an open-source license, welcoming contributions to our code.

:::

#### Citation

[ValidThoughts: View original post](https://validmind.com/blog/takeaways-from-open-source-in-finance-forum-future-of-fintech-oss-and-genai/){.button}