---
title: "ValidMind"
subtitle: "Technical Writing"
listing:
  - id: validmind-notebooks-author
    type: grid
    grid-columns: 2
    max-description-length: 250
    sort: false
    fields: [title, subtitle, description]
    contents:
    - path: https://validbeck.github.io/docs/developer/validmind-library.html#b58fc729-690b-4000-b19f-365a4093b2ff7b7b3c2076617220766d2e70726f64756374203e7d7d-for-validation
      title: "ValidMind for validation series"
      subtitle: "Jupyter Notebook"
      description: "Created as part of an initiative to highlight our validation features that we previously neglected to showcase."
    - path: https://validbeck.github.io/docs/notebooks/quickstart/quickstart_validation.html
      title: "Quickstart for validation"
      subtitle: "Jupyter Notebook"
      description: "Created as part of an initiative to highlight our validation features that we previously neglected to showcase."
  - id: validmind-notebooks-coauthor
    type: grid
    grid-columns: 2
    max-description-length: 250
    sort: false
    fields: [title, subtitle, description]
    contents:
    - path: https://validbeck.github.io/docs/notebooks/use_cases/validation/validate_application_scorecard.html
      title: "Validate an application scorecard model"
      description: "I partnered with our Head of Solutions Architecture to author this intermediate notebook, transforming his domain knowledge into a comprehensive use case sample."
      subtitle: "Jupyter Notebook"
    - path: https://validbeck.github.io/docs/notebooks/use_cases/agents/document_agentic_ai.html
      title: "Document an agentic AI system"
      subtitle: "Jupyter Notebook"
      description: "I teamed up with our Lead Machine Learning Engineer to author this intermediate notebook, transforming his domain knowledge into a comprehensive use case sample."
  - id: validmind-academy
    type: grid
    grid-columns: 3
    max-description-length: 250
    sort: false
    fields: [title, subtitle, description]
    contents:
    - path: https://validbeck.github.io/docs/training/developer-fundamentals/developer-fundamentals-register.html
      title: "Developer Fundamentals for ValidMind"
      subtitle: "Training"
    - path: https://validbeck.github.io/docs/training/validator-fundamentals/validator-fundamentals-register.html
      title: "Validator Fundamentals for ValidMind"
      subtitle: "Training"
    - path: https://validbeck.github.io/docs/training/administrator-fundamentals/administrator-fundamentals-register.html
      title: "Administrator Fundamentals for ValidMind"
      subtitle: "Training"
  - id: validmind-get-started
    type: grid
    grid-columns: 2
    max-description-length: 250
    sort: false
    fields: [title, subtitle]
    contents:
    - path: https://validbeck.github.io/docs/get-started/get-started.html
      title: "Get started with ValidMind"
      subtitle: "Tutorials"
    - path: https://validbeck.github.io/docs/get-started/developer/quickstart-developer.html
      title: "Quickstart — Development"
      subtitle: "Tutorials"
    - path: https://validbeck.github.io/docs/get-started/validator/quickstart-validator.html
      title: "Quickstart — Validation"
      subtitle: "Tutorials"
    - path: https://validbeck.github.io/docs/get-started/administrator/quickstart-administrator.html
      title: "Quickstart — Setup & Administration"
      subtitle: "Tutorials"
  - id: validmind-style
    type: grid
    grid-columns: 3
    max-description-length: 250
    sort: false
    fields: [title, subtitle, description]
    contents:
    - path: https://validbeck.github.io/docs/about/contributing/style-guide/style-guide.html
      title: "ValidMind style guide"
      subtitle: "Content Enablement"
    - path: https://validbeck.github.io/docs/about/contributing/style-guide/voice-and-tone.html
      title: "Voice and tone"
      subtitle: "Content Enablement"
    - path: https://validbeck.github.io/docs/about/contributing/style-guide/conventions.html
      title: "Conventions"
      subtitle: "Content Enablement"
  - id: validmind-templates
    type: grid
    grid-columns: 2
    max-description-length: 250
    sort: false
    fields: [title, subtitle, description]
    contents:
    - path: https://github.com/validbeck/validmind-library/tree/main/notebooks/templates
      title: "Jupyter Notebook template Quickstart"
      subtitle: "Content Enablement"
    - path: https://github.com/validbeck/validmind-library/blob/main/notebooks/templates/e2e-notebook.ipynb
      title: "End-to-end notebook template generation"
      subtitle: "Content Enablement"
  - id: validmind-workflows
    type: grid
    grid-columns: 3
    max-description-length: 250
    sort: false
    fields: [title, subtitle]
    contents:
    - path: https://validbeck.github.io/docs/guide/workflows/introduction-to-workflows.html
      title: "Introduction to workflows"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/workflows/workflow-step-types.html
      title: "Workflow step types"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/workflows/conditional-step-requirements.html
      title: "Conditional requirements"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/workflows/workflow-states.html
      title: "Workflow states"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/workflows/setting-up-workflows.html
      title: "Setting up workflows"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/workflows/manage-record-stages.html
      title: "Manage record stages"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/workflows/configure-workflows.html
      title: "Configure workflows"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/workflows/workflow-configuration-examples.html
      title: "Workflow configuration examples"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/workflows/working-with-workflows.html
      title: "Working with workflows"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/workflows/manage-workflows.html
      title: "Manage workflows"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/workflows/transition-workflows.html
      title: "Transition workflows"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/workflows/manage-workflow-tasks.html
      title: "Manage workflow tasks"
  - id: validmind-validation
    type: grid
    grid-columns: 3
    max-description-length: 250
    sort: false
    fields: [title, subtitle]
    contents:
    - path: https://validbeck.github.io/docs/guide/validation/managing-validation.html
      title: "Managing validation"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/validation/manage-validation-guidelines.html
      title: "Manage validation guidelines"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/validation/configure-assessment-options.html
      title: "Configure assessment options"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/validation/manage-artifact-types.html
      title: "Manage artifact types"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/validation/manage-artifact-severities.html
      title: "Manage artifact severities"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/validation/manage-artifact-fields.html
      title: "Manage artifact fields"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/validation/working-with-artifacts.html
      title: "Working with artifacts"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/validation/view-filter-artifacts.html
      title: "View and filter artifacts"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/validation/customize-artifact-layouts.html
      title: "Customize artifact layouts"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/validation/log-artifacts.html
      title: "Log artifacts"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/validation/update-artifacts.html
      title: "Update artifacts"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/validation/customize-artifact-overview-page.html
      title: "Customize artifact overview page"
      subtitle: "User Guides"
  - id: validmind-docs
    type: grid
    grid-columns: 3
    max-description-length: 250
    sort: false
    fields: [title, subtitle]
    contents:
    - path: https://validbeck.github.io/docs/guide/documentation/work-with-test-results.html
      title: "Work with test results"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/monitoring/work-with-metrics-over-time.html
      title: "Work with metrics over time"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/documentation/work-with-document-versions.html
      title: "Work with document versions"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/templates/managing-documents.html
      title: "Managing documents"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/templates/manage-document-types.html
      title: "Manage document types"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/templates/manage-documents.html
      title: "Manage documents"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/templates/customize-document-checker.html
      title: "Customize ValidMind Document Checker"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/templates/manage-text-block-library.html
      title: "Manage text block library"
      subtitle: "User Guides"
  - id: validmind-inventory
    type: grid
    grid-columns: 2
    max-description-length: 250
    sort: false
    fields: [title, subtitle]
    contents:
    - path: https://validbeck.github.io/docs/guide/inventory/manage-inventory-record-types.html
      title: "Manage inventory record types"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/inventory/edit-inventory-fields.html
      title: "Edit inventory fields"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/inventory/configure-record-interdependencies.html
      title: "Configure record interdependencies"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/inventory/archive-delete-records.html
      title: "Archive and delete records"
      subtitle: "User Guides"
  - id: validmind-reporting
    type: grid
    grid-columns: 2
    max-description-length: 250
    sort: false
    fields: [title, subtitle]
    contents:
    - path: https://validbeck.github.io/docs/guide/reporting/tracking-organization-activity.html 
      title: "Tracking organization activity"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/reporting/view-record-activity.html
      title: "View record activity"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/reporting/view-settings-activity.html
      title: "View settings activity"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/reporting/manage-custom-reports.html
      title: "Manage custom reports"
      subtitle: "User Guides"
  - id: validmind-config
    type: grid
    grid-columns: 3
    max-description-length: 250
    sort: false
    fields: [title, subtitle]
    contents:
    - path: https://validbeck.github.io/docs/guide/access/register-with-validmind.html
      title: "Register with ValidMind"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/configuration/managing-your-organization.html
      title: "Managing your organization"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/configuration/manage-platform-notifications.html
      title: "Manage platform notifications"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/configuration/manage-record-stakeholder-types.html
      title: "Manage record stakeholder types"
      subtitle: "User Guides"
    - path: https://validbeck.github.io/docs/guide/configuration/customize-your-dashboard.html
      title: "Customize your dashboard"
      subtitle: "User Guides"
---

{{< include /samples/single-source/validmind/_validmind.qmd >}}

For the samples below, I've selected only my best work as my contribution to ValidMind spanned too much content to collate in its entirety. 

::: {.callout}
Links below will take you to static versions of the content as last edited by Beck.

:::

## ValidMind Jupyter Notebooks

Jupyter Notebook use case demonstrations written for ValidMind's Python library.

::: {.panel-tabset}

### Authored

I owned the linked notebooks in this section from start to finish. 

:::{#validmind-notebooks-author}
:::


### Co-authored

I led the creation of these notebooks, supported by another team member as my subject matter expert.

:::{#validmind-notebooks-coauthor}
:::

:::

## ValidMind Training

Comprehensive interactive training cirriculums developed to onboard users onto ValidMind.

For the samples below, I was responsible for everything from cirriculum planning, to content, to design refinement, starting from sparse one-module drafts created by another writer. I included these samples as I owned at least 75% of the content. 

:::{#validmind-academy}
:::

## ValidMind User Guides

User guides produced as documentation and reference for ValidMind's core features.

For the samples below, I've selected only my best work where I authored the bulk of the content as my contribution to ValidMind spanned too much content to collate in its entirety. 

::: {.panel-tabset}

### Workflows

:::{#validmind-workflows}
:::

### Validation

:::{#validmind-validation}
:::

### Documentation & Templates

:::{#validmind-docs}
:::

### Inventory

:::{#validmind-inventory}
:::

### Reporting

:::{#validmind-reporting}
:::

### Access & Configuration

:::{#validmind-config}
:::


:::

## ValidMind Quickstarts

Intuitive quickstart guides developed to onboard users onto ValidMind.

I took a previously jumbled section of fragmented guides, with no clear learning outcomes and missing user role journeys, to a streamlined portal that empowered every type of new user. I owned all of the new quickstart guidance linked below from start to finish.

:::{#validmind-get-started}
:::

## ValidMind Enablement Content

Content produced to enable other creators to contribute to ValidMind's open-source.

::: {.panel-tabset}

### ValidMind Style Guide

One of the first things I did at ValidMind was establish and publish our documentation style guide, based off of a sparse internal draft of general writing guidelines.

:::{#validmind-style}
:::

### ValidMind Jupyter Notebooks

As Jupyter Notebooks operate as self-contained units, you're unable to easily single-source content that's repeated in other notebooks or documentation. 

To encourage other notebook authors to use our consistent ValidMind notebook structure, I created a Python script and an accompanying interactive notebook that generates a notebook draft with all the right bits and pieces.

:::{#validmind-templates}
:::

:::
