---
title: "ValidMind Developer Library"
subtitle: "Content Engineering"
categories: ["Content Architecture", "Developer Content", "Feature Documentation", "User Guides", "Jupyter Notebooks", "Quarto",  "Frontend Development"]
listing:
  - id: validmind-jupyter
    type: grid
    grid-columns: 1
    max-description-length: 250
    sort: false
    fields: [title, subtitle, description]
    contents:
    - ../../technical-writing/validmind/jupyter-notebooks.qmd
---

::: {.hidden}
I transformed our disorganized developer resources into a comprehensive reference with a clean, modern, and mobile-responsive design.
:::

Along with authoring the bulk of ValidMind’s user guidance content, I also transformed our disorganized developer resources into a comprehensive reference with a clean, modern, and mobile-responsive design.

{{< include /samples/single-source/validmind/_new-user.qmd >}}

## Situation

Before I joined ValidMind, our documentation site and associated resources did not have their own brand identity or design system. Along with the information being poorly organized, users did not receive visual cues when content types shifted.

Our open-source Python library (ValidMind Library) functionality was paired with our frontend application to form a complete product suite. Instead of standing alone, our developer resources were intertwined with the rest of the product documentation. 

Like our quickstart portal,^[[ValidMind Quickstarts](/samples/content-engineering/validmind/quickstarts.qmd)] most of the information contained in the developer resources was conceptual, not action-oriented, bombarding users with walls of text. Any helpful tutorials were buried under nested links in poorly organized sections, asking users to go searching for action-oriented information without guidance.

## Solution

As part of leading the redesign and reorganization of ValidMind's documentation,^[[ValidMind Documentation Redesign](/samples/content-engineering/validmind/redesign.qmd)] I gave the developer portal its own alternate, simplified design inspired by our checkmark logo to put the focus on the technical content:

- Cleaned up landing pages with clear, actionable links to helpful tutorials and other guidance.
- Comprehensive resources laid out in a reorganized sidebar navigation, with clear starter user journeys by role.

## Comparisons

### Developer Library

::: {.panel-tabset}

#### Before

The old developer resource section, asking you to scroll through a wall of conceptual information and hunt in the sidebar for scattered links with actionable instructions, which was also hidden on mobile devices by default:[^old-library]

[^old-library]: 

    ::: {.iframe url="https://validbeck.github.io/archive/guide/get-started-developer-framework.html" title="Previous ValidMind Developer Library Mobile View" zoom="100%" width="70%" new-window="false"}
    :::

::: {.iframe url="https://validbeck.github.io/archive/guide/get-started-developer-framework.html" title="Previous ValidMind Developer Library"}
:::

#### After

My new developer resource portal, with a cleaned up introduction, more comprehensive resources for both relevant user roles, and no hidden links on mobile devices:[^new-library]

[^new-library]: 

    ::: {.iframe url="https://validbeck.github.io/docs/developer/validmind-library.html" title="New ValidMind Developer Library Mobile View" zoom="100%" width="70%" new-window="false"}
    ::: 

::: {.iframe url="https://validbeck.github.io/docs/developer/validmind-library.html" title="New ValidMind Developer Library"}
:::

::: {.callout}

I authored both the validation quickstart and introduction to validation Jupyter Notebook series, and edited the older developer quickstart and developer introduction into a series that paired together with the validation journey.

:::

:::

::: {.column-margin}
:::{#validmind-jupyter}
:::

:::

### Testing

::: {.panel-tabset}

#### Before

wip

::: {.iframe url="https://validbeck.github.io/archive/guide/testing-overview.html" title="Previous ValidMind Library Testing"}
:::

#### After

designed and implemented this

::: {.iframe url="https://validbeck.github.io/docs/developer/how-to/testing-overview.html" title="New ValidMind Library Testing"}
:::

:::

### Features

::: {.panel-tabset}

#### Before

wip

::: {.iframe url="https://validbeck.github.io/archive/guide/testing-overview.html" title="Previous ValidMind Library Features"}
:::

#### After

designed and implemented this

::: {.iframe url="https://validbeck.github.io/docs/developer/how-to/feature-overview.html" title="New ValidMind Library Features"}
:::

:::

### Samples

::: {.panel-tabset}

#### Before

wip

::: {.iframe url="https://validbeck.github.io/archive/guide/samples-jupyter-notebooks.html" title="Previous ValidMind Library Samples"}
:::

#### After

designed and implemented this

::: {.iframe url="https://validbeck.github.io/docs/developer/samples-jupyter-notebooks.html" title="New ValidMind Library Samples"}
:::

:::

## Citation

[{{< fa brands github >}} Archive of `validmind/documentation` Developer Portal by Beck](https://github.com/validbeck/validmind-docs/tree/main/site/developer){target="_blank" .button}

::: {.callout}
You can learn more about my involvement with ValidMind's documentation and the impact I had on developer content under [Technical Writing](/samples/technical-writing/validmind/index.qmd#validmind-jupyter-notebooks).
:::