---
title: "ValidMind Quickstart Guides"
subtitle: "Content Engineering"
categories: ["Content Architecture", "Training & Onboarding", "Instructional Design", "Quarto", "Frontend Development"]
listing:
  - id: validmind-jupyter
    type: grid
    grid-columns: 1
    max-description-length: 250
    sort: false
    fields: [title, subtitle, description]
    contents:
    - ../../technical-writing/validmind/jupyter-notebooks.qmd
---

::: {.hidden}
I transformed ValidMind's cluttered and ill-defined quickstart experience with gaps in resources to a clean and comprehensive onboarding journey with clear learning outcomes that showcased the value of our product through interaction.

:::

Along with authoring the bulk of ValidMind's user guidance content, I also transformed our cluttered and ill-defined quickstart experience with gaps in resources to a clean and comprehensive onboarding journey with clear learning outcomes that showcased the value of our product through interaction.

{{< include /samples/single-source/validmind/_new-user.qmd >}}

## Situation

The quickstart journey offered by ValidMind before I joined was simply put, not very quick, and not very helpful in getting you started:

- Our solution was for developers, validators, and auditors, but the only guidance available was for developers.
- Most of the information was conceptual, not action-oriented, bombarding users with walls of text.
- Any action-oriented info was scattered into multiple guides, asking users click many links before starting tasks.

## Solution

A cleaned-up, uncluttered quickstart portal with no fluff:

- Quickstart journeys for all roles, each presented with explicit learning outcomes to set expectations.
- Quickstarts are only action-oriented, and consolidated into a single guide for each role. 
- Show, and not tell &mdash; value is demonstrated through interaction with the product, not through conceptual text.

::: {.callout}
## Along with redesigning the quickstart experience, I also owned the content of each quickstart in its entirety.

For the developer and validator quickstarts, I also authored the Jupyter Notebooks used in those journeys.
:::

::: {.column-margin}
:::{#validmind-jupyter}
:::

:::

## Comparisons

### Portal

::: {.panel-tabset}

#### Before

The old quickstart portal, asking you to scroll through a wall of conceptual information and hunt in the sidebar for scattered links with actionable instructions, which was also hidden on mobile devices by default:[^old-quickstarts]

[^old-quickstarts]: 

    ::: {.iframe url="https://validbeck.github.io/archive/guide/get-started.html" title="Previous ValidMind Quickstart Portal Mobile View" zoom="100%" width="70%" new-window="false"}
    :::

::: {.iframe url="https://validbeck.github.io/archive/guide/get-started.html" title="Previous ValidMind Quickstart Portal"}
:::

#### After

My new quickstart portal, with clearly defined user journeys and expected learning outcomes deliver in one page per role, and zero clutter or fluff, no hidden links on mobile devices:[^new-quickstarts]

[^new-quickstarts]: 

    ::: {.iframe url="https://validbeck.github.io/docs/get-started/get-started.html" title="New ValidMind Quickstart Portal Mobile View" zoom="100%" width="70%" new-window="false"}
    :::

::: {.iframe url="https://validbeck.github.io/docs/get-started/get-started.html" title="New ValidMind Quickstart Portal"}
:::

:::

### Guides

::: {.panel-tabset}

#### Before

The old developer only quickstart was not really a quickstart at all, but rather a collation of scattered links to other guides with no connecting narrative:

::: {.iframe url="https://validbeck.github.io/archive/guide/quickstart.html" title="Previous Developer Only Quickstart"}
:::

#### After

My new developer quickstart, guiding users through actions with clear learning outcomes in a cohesive journey, without requiring them to leave the context simply to complete instructions:

::: {.iframe url="https://validbeck.github.io/docs/get-started/developer/quickstart-developer.html" title="New Developer Quickstart"}
:::

::: {.callout}
The instructions in the new quickstarts are also singled-sourced,^[[Portfolio Framework](/samples/content-engineering/personal/portfolio/framework.qmd#content)] meaning that information for the same task is consistent across the documentation when it is displayed in multiple places, such as in training or the full user guides for that feature.

:::

:::

## Citation

[{{< fa brands github >}} Archive of `validmind/documentation` Quickstarts by Beck](https://github.com/validbeck/validmind-docs/tree/main/site/get-started/){target="_blank" .button}

::: {.callout}
You can learn more about my involvement with ValidMind's documentation and the impact I had on training and onboarding collateral under [Technical Writing](/samples/technical-writing/validmind/index.qmd#validmind-quickstarts).
:::
