---
title: "SaaSquatch Integrations"
subtitle: "Feature Documentation"
categories: ["Feature Documentation", "User Guides", "Integrations", "Salesforce", "CRMs", "Stripe", "Recurly", "Tango Card", "Payment Providers", "Reward Providers", "Referrals & Attributions", "eCommerce", "Software as a Service", "Marketing Technology", "SaaSquatch"]
listing:
  - id: saasquatch-sfdc
    type: grid
    grid-columns: 2
    max-description-length: 250
    sort: false
    fields: [title, subtitle, description]
    contents:
      - sfdc/invocable-methods.qmd
      - sfdc/integration-guide.qmd
      - sfdc/attribution-lookup.qmd
      - sfdc/user-account-ids.qmd
  - id: saasquatch-integrations
    type: grid
    grid-columns: 3
    max-description-length: 250
    sort: false
    fields: [title, subtitle, description]
    contents:
      - stripe.qmd
      - recurly.qmd
      - tango-card.qmd
---

During my tenure at SaaSquatch, I became the company Subject Matter Expert for many of our custom integrations, including our intergration for Salesforce which I helped develop.

## Salesforce 

Before I worked at SaaSquatch, I had never used Salesforce (SFDC). Very quickly after onboarding, I helped develop our SFDC integration during my time as a **Solutions Architect** as part of custom work for a client. 

Below are a few samples of the guides I produced to assist with custom implementations utilising our SFDC integration:

:::{#saasquatch-sfdc}
:::


## Other

Below are a few samples of the guides I produced to assist with custom payment provider and rewards integrations, written based on provided Cucumber specs and several independent UATs I performed in order to understand the features fully:

:::{#saasquatch-integrations}
:::
