---
format: html
minimal: true
---

**24 guests**

::: {.poetry}
We sit wanting in staid Summer,<br>
Waiting under that scorched sun.<br>
When the wolfberries dangle so<br>
Like little lanterns of light from<br>
Our first chance meeting under <br>
A sky marred only by a magpie.<br><br>

For abundant Autumn<br>
To slake our longing,<br>
To unite<br>
That which was <br>
Divided<br>
By the mansion of the stars. <br>
You and I weave<br>
A tale everlasting,<br>
We hope.<br>
And dream <br>
Of two cranes,<br>
Soaring<br>
As we adore the dappled 
Harvest Moon.<br><br>

From that same heaven<br>
Descends Winter’s bitter hoarfrost<br>
His voice, crisp and calamitous <br>
Against the calm of unglazed porcelain.<br> 
Each year, twenty-four guests we host in turn,<br>
Each more solemn than the last.<br>
We wonder and wonder and wonder and wonder and wonder<br>
If this will end or if we might end. Not even the <br>
Syrupy persimmons, cultivated by our tender care<br>
Can relieve the sting of stagnation with their cloying embrace.<br>
Without you, I find the effigy of a crippled cuckoo,<br>
Its call long since lost to a memory of when you were here.<br><br>

But still<br>
Before I know it,<br>
One day I hear<br>
The striking, strident song<br>
Of a gander in the garden I once shared with you.<br>
Across the pond too shallow to sink my wistful, wretched form&mdash;<br>
Floats a flurry of felled peach blossoms, and a reflection of that aching, azure sky. <br><br><br>

:::
