---
format: html
minimal: true
---

**past**

::: {.poetry}

It seems so far away, this memory of mine: <br>
just shy of a decade <br>
&emsp;old<br>
& yet&mdash;<br>
it feels like <br>
&emsp;a lifetime <br><br>

&emsp;&emsp;away.<br>

Certainly<br>
the you & I <br>
from that era are <br>
&emsp;dead<br><br>

One day<br>
we play hide-&-seek <br>
for the last time <br>
&emsp;before <br>
parting ways for <br>
good<br>
our hopes & aspirations <br>
&emsp;tucked away <br>
in a corner of a secret <br>
garden<br>
&emsp;&emsp;never <br><br>

to be found.<br><br>

Strange<br>
&emsp;isn’t it<br><br>

That we hold such elaborate funerals for the lives that were lived <br>
&emsp;& then lost <br>
but for the lives that were lost <br>
before they were ever <br>
&emsp;lived<br>
we say to ourselves that there is no use in mourning <br>
what was not meant <br><br>

&emsp;&emsp;to be.<br><br>

Stranger still<br>
every day we say an eerily nonchalant goodbye to <br>
&emsp;yesterday<br>
to the echo of our souls <br>
now buried by the sands of time&mdash;<br>
in tomorrow <br>
there is no room <br>
&emsp;&emsp;for <br><br>

&emsp;&emsp;&emsp;the past. <br><br>

No graves are dug<br>
no rites are performed<br>
for that which will never be <br>
&emsp;again<br><br>

We simply <br>
enclose our grief carefully <br>
in a coffin deep within<br>
&emsp;our hearts<br>
in a mausoleum of memories <br>
we visit only <br>
on the nights <br>
that are too quiet<br>
&emsp;& <br>
&emsp;&emsp;too<br><br>
 
&emsp;&emsp;&emsp;long.<br><br>

When we look up <br>
at the painfully fulgent moon<br>
&emsp;round & full <br>
in the relentless dark<br>
in its shadows <br>
&emsp;we see <br>
the vestiges <br>
&emsp;&emsp;of <br>
&emsp;&emsp;&emsp;days <br>

&emsp;&emsp;&emsp;&emsp;bygone<br><br><br>

::: 
