---
format: html
minimal: true
---

**Persimmons**

::: {.poetry}
I do not know how old I am<br>
When I first taste their putrid pulp<br>
Only that I already know by then<br>
To silently swallow the taste <br>
Of sickening dread,<br>
When their silken skins slide over my tongue<br>
Lest I wish to be rewarded with the shrill sound of <br>
Censure.<br><br>

For my piety I receive many more<br>
Of those unctuous orbs of oozing,<br>
Weeping <br>
Wicked, sorry excuses<br>
For a mother’s <br>
Warmth.<br>
 
I come to resent the monstrous Moon,<br>
For her indifferent gaze <br>
When those groves of gentle green turn<br>
To that harsh umbrage of harvest<br>
A chilling courtesy, a quiet caution of my fate:<br>
Soon left alone <br>
Under a barren sky<br>
With only those loathsome lanterns <br>
Of offending ochre-red.<br>
On each slick, sticky bite<br>
On each spine-shattering squelch<br>
I am promised a life of everlasting prosperity<br>
If only I should meekly receive the grand gift of<br>
Obedience.<br><br>
   
But how can I bear with open arms<br>
A present so ponderous<br>
That I must genuflect with monumental grace?<br>
How could I possibly don that damned cloak <br>
Embroidered so thick with <br>
Expectation?<br><br>

Instead of taking my fill of those plump persimmons<br>
Grotesque and gorged by our suffocating superstitions<br>
Instead of their sanguine sweetness <br>
I would rather drown in a dark brew of cinnabarite<br>
Let that vibrant vermillion ruddle <br>
A heart so fettered by fury<br>
And unravel our tangled<br>
Heritage.<br><br><br>


:::