---
format: html
minimal: true
---

**Taken**

::: {.poetry}
At seven-teen,<br>
I read what was taken from Arabella<br>
Later,<br>
I peer through Wheelock's <br>
that same night<br>
in the dim hours of even-gloam:<br>
&emsp;*rapio, rapere, rapui, raptum*&mdash;<br>
I chant with the solemnity of the Bede<br>
&emsp;to seize, I seize, I have seized, hav-<br>
ing been seized.<br><br>

I do not remember, <br>
when I am first seized <br>
on a night when the moon is ach-<br>
&emsp;ingly full&mdash;<br>
by a longing for a home I have never truly known.<br>
      (*rapior.*)<br><br>

I wonder too much later still<br>
How many kingdoms suffereth violence&mdash;<br>
&emsp;*et violenti rapiunt illa?*<br>
As for mine,<br>
Borne away for the price of a pit-<br>
&emsp;iful poppy,<br>
I feel a grief I cannot truly claim as my own.<br><br>

For a time,<br>
I hide away the dreams of fair Oothoon<br>
tucked within her pages I revered so dearly<br>
a shame that I cannot name&mdash;<br>
For my impeity,<br>
I suppose?<br><br>

For drowning myself in that reckless vision<br>
That welcomed neither that bonny maid nor I.<br><br>

For losing tongues I was never given,<br>
For taking refuge in the songs <br>
&emsp;of that same Albion<br>
that seized by violent force<br>
a city-state<br>
&emsp;that never quite was <br>
and will never be again.<br><br><br>

:::

