---
format: html
minimal: true
---

**Wonder**

::: {.poetry}
what a Wonder it is<br>
to Know<br><br>
the sunrises You were always meant to see<br>
the winds across that whirling, raging ocean <br>
from which You clambered<br>
with fang<br>
&emsp;and claw<br>
&emsp;&emsp;and <br>
a soft, capricious Heart<br><br>
what a Wonder it is<br>
to Know<br><br>
each drop of rain by teasing touch <br>
every incandescent star,<br>
&emsp;fleeting dream,<br>
&emsp;&emsp;vainglorious wish<br>
hung so desperately upon the mantle of the sky<br><br>

what a Wonder it is<br>
to Know<br>
the silence still upon a lake,<br>
the flicker of frost <br>
courting the sentinel of<br>
&emsp;Autumn's last citadel<br>
&emsp;&emsp;&emsp;&emsp;then,<br><br>
the sanguine taste of Spring's <br>
first audacious blooms<br><br>
what a Wonder it is<br>
to Know<br><br>
when that sea comes once again to claim<br>
&emsp;what has always and<br>
&emsp;&emsp;will always be Yours<br>
&emsp;&emsp;&emsp;as it has been since you were You<br>
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;who asked<br><br>
Oh<br><br>
how?<br>
&emsp;&emsp;how is it<br><br>
To be?<br><br>
&emsp;&emsp;&emsp;A Wonder.<br><br><br>

:::