project:
  type: website
  output-dir: ../output

metadata-files:
  - samples/content-engineering/_sidebar.yaml
  - samples/technical-writing/_sidebar.yaml
  - samples/copywriting/_sidebar.yaml
  - samples/developer-advocacy/_sidebar.yaml

website:
  title: "Beck Chan &diams; Portfolio"
  navbar:
    left:
      - samples/content-engineering/index.qmd
      - samples/technical-writing/index.qmd
      - samples/copywriting/index.qmd
      - samples/developer-advocacy/index.qmd
    right:
      - cv.qmd
      - changelog.qmd

  sidebar: 
    style: docked
    contents:
      - text: "About"
      - cv.qmd
      - changelog.qmd

  search:
    location: navbar

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true