project:
  type: website
  output-dir: ../output

website:
  title: "Beck Chan &diams; Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true